#!/usr/bin/env python3
"""
Generate bin/plot_trajectory wrapper script.

Usage:
  python setup.py

This creates:
  bin/plot_trajectory

The wrapper adds ../src to sys.path and calls frames.main().
"""

from __future__ import annotations
from pathlib import Path
import os
import stat
import sys


WRAPPER = r"""#!/usr/bin/env python3
# Auto-generated by setup.py
import os
import sys
from pathlib import Path

# Add ../src to sys.path so we can import src/frames.py and src/ffmpeg.py
HERE = Path(__file__).resolve().parent
SRC  = (HERE / ".." / "src").resolve()
sys.path.insert(0, str(SRC))

import frames  # src/frames.py

if __name__ == "__main__":
    raise SystemExit(frames.main())
"""


def make_executable(path: Path) -> None:
    st = os.stat(path)
    os.chmod(path, st.st_mode | stat.S_IXUSR | stat.S_IXGRP | stat.S_IXOTH)


def main() -> int:
    root = Path(__file__).resolve().parent
    bin_dir = root / "bin"
    bin_dir.mkdir(parents=True, exist_ok=True)

    out = bin_dir / "plot_trajectory"
    out.write_text(WRAPPER, encoding="utf-8")
    make_executable(out)

    print(f"Wrote {out}")
    print("Add this to your PATH if needed:")
    print(f"  export PATH={bin_dir}:$PATH")
    return 0


if __name__ == "__main__":
    sys.exit(main())

